#  Some Interesting PyTorch tensor operations with Examples 

## PyTorch:


PyTorch is a Python-Python based scientific computing package. It's mainly used for applications such as computer vision and natural language processing. The flexibility of PyTorch allow easy integration of new data types and algorithms, and the framework is also efficient and scalable. It was designed to minimize the number of computations required and to be compatible with a variety of hardware architectures. Two broad purposes of PyTorch are:

* A replacement for NumPy to use the power of GPUs and other accelerators.
* An automatic differentiation library that is useful to implement neural networks.


## Tensors

A tensor is a number, vector. matrix or any n-dimensional array. These are the fundamental data structures in deep learning, which are very similar to arrays and matrics, with which we can efficiently perform mathematical operations on large sets of data. A tensor can be represented as a matrix, but also as a vector, a scalar, or a higher-dimensional array. 

To make it easier to visualize, we can think of a tensor as a simple array containing scalars or other arrays. On PyTorch, a tensor is a structure very similar to a **ndarry**, with the difference that they are capable of running on a GPU, which dramatically speeds up the computational process. 

In [1]:
#importing libraries

import torch
import numpy as np

## Tensor Operations

## Function 1 - torch.tensor

To create tensors with Pytorch we can simply use the tensor() method:

**Syntax:**

torch.tensor(Data)

In [2]:
# Example 1 

torch.tensor([[3, 6], [2, 4.]])

tensor([[3., 6.],
        [2., 4.]])

In [4]:
# Example 2 

a_data = [[1., 2., 3.], [4, 5, 6]] 
a = torch.tensor(a_data) 
print(a)


tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [3]:
# Example 3 - breaking
torch.tensor([[1, 2], [3, 4, 5]]) # No of element should be same

ValueError: expected sequence of length 2 at dim 1 (got 3)

## Function 2 - randint() 

The randint() method returns a tensor filled with random integers generated uniformly between low (inclusive) and high (exclusive) for a given shape. The shape is given by the user which can be a tuple or a list with non-negative members. The default value for low is 0. When only one int argument is passed, low gets the value 0, by default, and high gets the passed value.

**Syntax:**

torch.randint(low,high,shape)

In [9]:
# Example 1 

randint_tensor_a = torch.randint(2,5, (2,2)) 
print(randint_tensor_a)

tensor([[2, 4],
        [2, 4]])


In [10]:
# Example 2 - working

randint_tensor = torch.randint(0,3, (3,2)) 
print(randint_tensor)

tensor([[1, 2],
        [1, 2],
        [2, 0]])


In [11]:
# Example 3 - breaking (to illustrate when it breaks)

randint_tensor_c = torch.randint(1, (3)) 
print(randint_tensor)



TypeError: randint(): argument 'size' (position 2) must be tuple of ints, not int

## Function 3 - complex()

The complex() method takes two arguments (real and imag) and returns a complex tensor with its real part equal to real and its imaginary part equal to imag where both real and imag are tensors having the same datatype and same shape.

**Syntax:**

torch.complex(real tensor,another real tensor which is to be used as imaginary part)

In [12]:
# Example 1 

a_real = torch.rand(2, 2) 
print(a_real) 
a_imag = torch.rand(2, 2) 
print(a_imag) 
a_complex_tensor = torch.complex(a_real, a_imag) 
print(a_complex_tensor)

tensor([[0.4356, 0.7506],
        [0.5335, 0.6262]])
tensor([[0.1342, 0.0804],
        [0.2047, 0.0685]])
tensor([[0.4356+0.1342j, 0.7506+0.0804j],
        [0.5335+0.2047j, 0.6262+0.0685j]])


In [13]:
# Example 2 

b_real = torch.rand(4, 3) 
print(b_real) 
b_imag = torch.rand(4, 3) 
print(b_imag) 
b_complex_tensor = torch.complex(b_real, b_imag) 
print(b_complex_tensor)

tensor([[0.5516, 0.3566, 0.1326],
        [0.0870, 0.7649, 0.4876],
        [0.0647, 0.9627, 0.7627],
        [0.5156, 0.8200, 0.3522]])
tensor([[0.4803, 0.5671, 0.8102],
        [0.3770, 0.5989, 0.8159],
        [0.4721, 0.8255, 0.5843],
        [0.9182, 0.7669, 0.1143]])
tensor([[0.5516+0.4803j, 0.3566+0.5671j, 0.1326+0.8102j],
        [0.0870+0.3770j, 0.7649+0.5989j, 0.4876+0.8159j],
        [0.0647+0.4721j, 0.9627+0.8255j, 0.7627+0.5843j],
        [0.5156+0.9182j, 0.8200+0.7669j, 0.3522+0.1143j]])


In [24]:
# Example 3 - breaking

real = torch.rand(1, 2) 
print(real) 
imag = torch.rand(0) 
print(imag) 
complex_tensor = torch.complex(real, imag) 
print(complex_tensor)

tensor([[0.2599, 0.4582]])
tensor([])


RuntimeError: The size of tensor a (2) must match the size of tensor b (0) at non-singleton dimension 1

## Function 4 - reshape()

This method allows us to change the shape with the same data and number of elements as self but with the specified shape, which means it returns the same data as the specified array, but with different specified dimension sizes.

**Syntax:**

torch.reshape(input, shape)

In [25]:
# Example 1 

a = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])
print(a) 
print(a.reshape([4, 2]))

tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [26]:
# Example 2

a = torch.tensor([[1,2,3],[4,5,6]])
torch.reshape(a, (6,1))

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [27]:
# Example 3 - breaking 

a = torch.tensor([[1,2,3],[4,5,6]])
torch.reshape(a, (6))

TypeError: reshape(): argument 'shape' (position 2) must be tuple of ints, not int

## Function 5 - view() 

view() is used to change the tensor in two-dimensional format IE rows and columns. We have to specify the number of rows and the number of columns to be viewed.

**Syntax:** 

tensor.view(no_of_rows,no_of_columns)

In [29]:
# Example 1

a=torch.FloatTensor([24, 56, 10, 20, 30, 
                     40, 50, 1, 2, 3, 4, 5])  

print(a)
print(a.view(4, 3))


tensor([24., 56., 10., 20., 30., 40., 50.,  1.,  2.,  3.,  4.,  5.])
tensor([[24., 56., 10.],
        [20., 30., 40.],
        [50.,  1.,  2.],
        [ 3.,  4.,  5.]])


In [33]:
# Example 2 

b = torch.FloatTensor([24, 56, 10, 20, 30,
                     40, 50, 1, 2, 3])  
 
print(b)
print(b.view(5, 2))


tensor([24., 56., 10., 20., 30., 40., 50.,  1.,  2.,  3.])
tensor([[24., 56.],
        [10., 20.],
        [30., 40.],
        [50.,  1.],
        [ 2.,  3.]])


In [34]:
# Example 3 - breaking


c = torch.FloatTensor([24, 56, 10, 20, 30,
                     40, 50, 1, 2, 3])  
 
print(c)
print(c.view(6, 2))

tensor([24., 56., 10., 20., 30., 40., 50.,  1.,  2.,  3.])


RuntimeError: shape '[6, 2]' is invalid for input of size 10

## Function 6 - take()

Returns a new tensor with the elements of input at the given indices. The input tensor is treated as if it were viewed as a 1-D tensor. The result takes the same shape as the indices


**Syntax:**

torch.take(input, index)

In [35]:
# Example 1 

a = torch.tensor([[1,2,3],
                  [3, 4,7],
                  [4,5,6]])
torch.take(a, torch.tensor([1,4,5]))

tensor([2, 4, 7])

In [36]:
# Example 2 

a = torch.tensor([[1,2,3],
                  [3, 4,7],
                  [4,5,6]])
torch.take(a, torch.tensor([0,3,6,8,5]))

tensor([1, 3, 4, 6, 7])

In [37]:
# Example 3 - breaking 

a = torch.tensor([[1,2,3],
                  [3, 4,7],
                  [4,5,6]])
torch.take(a, torch.tensor([0,3,6,8,10]))

IndexError: out of range: tried to access index 10 on a tensor of 9 elements.

## Function 7 - .unbind()

It's used to removes a tensor dimension. It will returns a tuple of all slices along a given dimension, already without it.

**Syntax:**

torch.unbind(input, dim=0)

In [38]:
# Example 1 

a = torch.tensor([[1,2,3],
                  [3, 4,7],
                  [4,5,6]])
torch.unbind(a)

(tensor([1, 2, 3]), tensor([3, 4, 7]), tensor([4, 5, 6]))

In [39]:
# Example 2 

a = torch.tensor([[1,2,3],
                  [3, 4,7],
                  [4,5,6]])
torch.unbind(a, 1)

(tensor([1, 3, 4]), tensor([2, 4, 5]), tensor([3, 7, 6]))

In [41]:
# Example 3 - breaking

a = torch.tensor([[1,2,3],
                  [3, 4,7],
                  [4,5,6]])
torch.unbind(a, 2)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

## Function 8 - reciprocal()

It's returns a new tensor with the reciprocal of the elements of input.

**Syntax:**

torch.reciprocal(input, out=None) 

In [42]:
# Example 1 

torch.reciprocal(torch.tensor([[1.6,2.5],[3,4],[5,6]]))

tensor([[0.6250, 0.4000],
        [0.3333, 0.2500],
        [0.2000, 0.1667]])

In [43]:
# Example 2 

a = torch.tensor([[1.0,2],[3,4],[5,6]])
torch.reciprocal(a)

tensor([[1.0000, 0.5000],
        [0.3333, 0.2500],
        [0.2000, 0.1667]])

In [49]:
# Example 3 - breaking 
a = torch.tensor([[1,2,3],
                  [3, 4,7],
                  [1,5,6]])
torch.reciprocal(a,1)

TypeError: reciprocal() takes 1 positional argument but 2 were given

## Function 9 - torch.t()

Transposition in tensor operations is the process of flipping the axes of a tensor. It involves exchanging the rows and columns of a 2D tensor or more generally, the axes of a tensor of any dimension.

**Syntax:**

torch.t() 

In [57]:
# Example 1 

E = torch.tensor([ [3, 8], [5, 6]])
F = torch.t(E)
print(E)
print(F)

tensor([[3, 8],
        [5, 6]])
tensor([[3, 5],
        [8, 6]])


In [53]:
# Example 2 

E = torch.tensor([[ 2, 5], [ 4, 8], [ 6, 10]])
F = torch.t(E)
print(E)
print(F)

tensor([[ 2,  5],
        [ 4,  8],
        [ 6, 10]])
tensor([[ 2,  4,  6],
        [ 5,  8, 10]])


In [56]:
# Example 3 - breaking 

E = torch.tensor([ [3], [5, 6]])
F = torch.t(E)
print(E)
print(F)

ValueError: expected sequence of length 1 at dim 1 (got 2)

## Function 10 - cat()

Concatenation in tensor operations is the process of joining two or more tensors along a specific dimension to form a larger tensor. The resulting tensor has a new dimension that is the concatenation of the original dimensions of the input tensors.


**Syntax:**

torch.cat() 

In [59]:
# Example 1 

a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6]])

c = torch.cat((a, b), dim=0)

print(c)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [62]:
# Example 2 


a = torch.tensor([[1, 2, 3], [3, 4, 9]])
b = torch.tensor([[5, 6], [4, 6]])

c = torch.cat((a, b), dim=1)

print(c)

tensor([[1, 2, 3, 5, 6],
        [3, 4, 9, 4, 6]])


In [61]:
# Example 3 - breaking 


a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6]])

c = torch.cat((a, b), dim=3)

print(c)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 3)

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* Difference between a matrix and a tensor: https://medium.com/@quantumsteinke/whats-the-difference-between-a-matrix-and-a-tensor-4505fbdc576c
* https://gist.github.com/jonhare/d98813b2224dddbb234d2031510878e1?permalink_comment_id=3166373